import { Types } from 'mongoose';

import { TxCategory } from '@/models/index.js';

/**
 * ----------------- Default Transaction Category List -----------------
 * Each category defines its accounting impact and cash flow behavior.
 */

export const defaultTxCategoryList = [
  /* ======================== CYLINDERS =========================== */
  {
    code: 'cylinder_sale_cash',
    name: 'Cylinder Sale (Cash)',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '4100-REV-CYL',
    descriptionTemplate: 'Cash sale of {{quantity}} cylinders to {{customerName}}',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'cylinder_sale_credit',
    name: 'Cylinder Sale (Credit)',
    debitAccountCode: '1100-ASSET-AR',
    creditAccountCode: '4100-REV-CYL',
    descriptionTemplate: 'Credit sale of {{quantity}} cylinders to {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_swap_retail',
    name: 'Cylinder Swap (Retail)',
    debitAccountCode: '1201-INVENTORY-CYL-FULL',
    creditAccountCode: '1202-INVENTORY-CYL-EMPTY',
    descriptionTemplate: 'Customer swapped {{quantity}} empty cylinders for full ones',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_swap_empty',
    name: 'Cylinder Swap (Empty Return)',
    debitAccountCode: '1202-INVENTORY-CYL-EMPTY',
    creditAccountCode: '1201-INVENTORY-CYL-FULL',
    descriptionTemplate: 'Returned {{quantity}} empty cylinders from {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_swap_defected',
    name: 'Cylinder Swap (Defected)',
    debitAccountCode: '1203-INVENTORY-CYL-DEFECTED',
    creditAccountCode: '1201-INVENTORY-CYL-FULL',
    descriptionTemplate: 'Swapped {{quantity}} defected cylinders',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_purchase_wholesale_cash',
    name: 'Cylinder Purchase (Cash)',
    debitAccountCode: '1201-INVENTORY-CYL-FULL',
    creditAccountCode: '1000-ASSET-CASH',
    descriptionTemplate: 'Purchased {{quantity}} cylinders (cash)',
    categoryType: 'cash_outflow',
    isActive: true,
  },
  {
    code: 'cylinder_purchase_wholesale_ap',
    name: 'Cylinder Purchase (Accounts Payable)',
    debitAccountCode: '1201-INVENTORY-CYL-FULL',
    creditAccountCode: '2101-AP-SUPPLIERS',
    descriptionTemplate: 'Cylinder purchase on credit from {{supplierName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_payment_to_supplier',
    name: 'Cylinder Supplier Payment',
    debitAccountCode: '2101-AP-SUPPLIERS',
    creditAccountCode: '1000-ASSET-CASH',
    descriptionTemplate: 'Paid supplier {{supplierName}} for cylinder dues',
    categoryType: 'cash_outflow',
    isActive: true,
  },
  {
    code: 'cylinder_adjustment_in',
    name: 'Cylinder Adjustment (In)',
    debitAccountCode: '1201-INVENTORY-CYL-FULL',
    creditAccountCode: '9999-MISC-EXPENSE',
    descriptionTemplate: 'Inventory adjustment: added {{quantity}} cylinders',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_adjustment_out',
    name: 'Cylinder Adjustment (Out)',
    debitAccountCode: '9999-MISC-EXPENSE',
    creditAccountCode: '1201-INVENTORY-CYL-FULL',
    descriptionTemplate: 'Inventory adjustment: removed {{quantity}} cylinders',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_sale_discount',
    name: 'Cylinder Sale Discount',
    debitAccountCode: '4201-REV-DISCOUNT',
    creditAccountCode: '4100-REV-CYL',
    descriptionTemplate: 'Applied discount on cylinder sale for {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_return',
    name: 'Cylinder Return',
    debitAccountCode: '1201-INVENTORY-CYL-FULL',
    creditAccountCode: '1100-ASSET-AR',
    descriptionTemplate: 'Returned {{quantity}} cylinders from {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'cylinder_internal_transfer',
    name: 'Cylinder Internal Transfer',
    debitAccountCode: '1501-ASSET-INTERNAL-TRANSFER',
    creditAccountCode: '1201-INVENTORY-CYL-FULL',
    descriptionTemplate: 'Transferred {{quantity}} cylinders internally between stores',
    categoryType: 'non_cash',
    isActive: true,
  },

  /* ======================== REGULATORS ========================== */
  {
    code: 'regulator_sale_cash',
    name: 'Regulator Sale (Cash)',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '4101-REV-REG',
    descriptionTemplate: 'Cash sale of {{quantity}} regulators to {{customerName}}',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'regulator_sale_credit',
    name: 'Regulator Sale (Credit)',
    debitAccountCode: '1100-ASSET-AR',
    creditAccountCode: '4101-REV-REG',
    descriptionTemplate: 'Credit sale of {{quantity}} regulators to {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_swap_retail',
    name: 'Regulator Swap (Retail)',
    debitAccountCode: '1300-INVENTORY-REG',
    creditAccountCode: '1301-INVENTORY-REG-DEFECTED',
    descriptionTemplate: 'Customer swapped defected regulators for new ones',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_swap_defected',
    name: 'Regulator Swap (Defected)',
    debitAccountCode: '1301-INVENTORY-REG-DEFECTED',
    creditAccountCode: '1300-INVENTORY-REG',
    descriptionTemplate: 'Swapped {{quantity}} defected regulators',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_purchase_wholesale_cash',
    name: 'Regulator Purchase (Cash)',
    debitAccountCode: '1300-INVENTORY-REG',
    creditAccountCode: '1000-ASSET-CASH',
    descriptionTemplate: 'Purchased {{quantity}} regulators (cash)',
    categoryType: 'cash_outflow',
    isActive: true,
  },
  {
    code: 'regulator_purchase_wholesale_ap',
    name: 'Regulator Purchase (Accounts Payable)',
    debitAccountCode: '1300-INVENTORY-REG',
    creditAccountCode: '2101-AP-SUPPLIERS',
    descriptionTemplate: 'Regulator purchase on credit from {{supplierName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_payment_to_supplier',
    name: 'Regulator Supplier Payment',
    debitAccountCode: '2101-AP-SUPPLIERS',
    creditAccountCode: '1000-ASSET-CASH',
    descriptionTemplate: 'Paid supplier {{supplierName}} for regulators',
    categoryType: 'cash_outflow',
    isActive: true,
  },
  {
    code: 'regulator_adjustment_in',
    name: 'Regulator Adjustment (In)',
    debitAccountCode: '1300-INVENTORY-REG',
    creditAccountCode: '9999-MISC-EXPENSE',
    descriptionTemplate: 'Added {{quantity}} regulators to inventory',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_adjustment_out',
    name: 'Regulator Adjustment (Out)',
    debitAccountCode: '9999-MISC-EXPENSE',
    creditAccountCode: '1300-INVENTORY-REG',
    descriptionTemplate: 'Removed {{quantity}} regulators from inventory',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_sale_discount',
    name: 'Regulator Sale Discount',
    debitAccountCode: '4201-REV-DISCOUNT',
    creditAccountCode: '4101-REV-REG',
    descriptionTemplate: 'Applied discount on regulator sale for {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_return',
    name: 'Regulator Return',
    debitAccountCode: '1300-INVENTORY-REG',
    creditAccountCode: '1100-ASSET-AR',
    descriptionTemplate: 'Returned {{quantity}} regulators from {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'regulator_internal_transfer',
    name: 'Regulator Internal Transfer',
    debitAccountCode: '1501-ASSET-INTERNAL-TRANSFER',
    creditAccountCode: '1300-INVENTORY-REG',
    descriptionTemplate: 'Transferred {{quantity}} regulators internally',
    categoryType: 'non_cash',
    isActive: true,
  },

  /* ========================== STOVES ============================ */
  {
    code: 'stove_sale_cash',
    name: 'Stove Sale (Cash)',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '4102-REV-STOVE',
    descriptionTemplate: 'Cash sale of {{quantity}} stoves to {{customerName}}',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'stove_sale_credit',
    name: 'Stove Sale (Credit)',
    debitAccountCode: '1100-ASSET-AR',
    creditAccountCode: '4102-REV-STOVE',
    descriptionTemplate: 'Credit sale of {{quantity}} stoves to {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_swap_retail',
    name: 'Stove Swap (Retail)',
    debitAccountCode: '1400-INVENTORY-STOVE',
    creditAccountCode: '1402-INVENTORY-STOVE-DEFECTED',
    descriptionTemplate: 'Swapped {{quantity}} defected stoves',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_swap_defected',
    name: 'Stove Swap (Defected)',
    debitAccountCode: '1402-INVENTORY-STOVE-DEFECTED',
    creditAccountCode: '1400-INVENTORY-STOVE',
    descriptionTemplate: 'Marked {{quantity}} stoves as defected',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_purchase_wholesale_cash',
    name: 'Stove Purchase (Cash)',
    debitAccountCode: '1400-INVENTORY-STOVE',
    creditAccountCode: '1000-ASSET-CASH',
    descriptionTemplate: 'Purchased {{quantity}} stoves (cash)',
    categoryType: 'cash_outflow',
    isActive: true,
  },
  {
    code: 'stove_purchase_wholesale_ap',
    name: 'Stove Purchase (Accounts Payable)',
    debitAccountCode: '1400-INVENTORY-STOVE',
    creditAccountCode: '2101-AP-SUPPLIERS',
    descriptionTemplate: 'Stove purchase on credit from {{supplierName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_payment_to_supplier',
    name: 'Stove Supplier Payment',
    debitAccountCode: '2101-AP-SUPPLIERS',
    creditAccountCode: '1000-ASSET-CASH',
    descriptionTemplate: 'Paid supplier {{supplierName}} for stoves',
    categoryType: 'cash_outflow',
    isActive: true,
  },
  {
    code: 'stove_adjustment_in',
    name: 'Stove Adjustment (In)',
    debitAccountCode: '1400-INVENTORY-STOVE',
    creditAccountCode: '9999-MISC-EXPENSE',
    descriptionTemplate: 'Added {{quantity}} stoves to inventory',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_adjustment_out',
    name: 'Stove Adjustment (Out)',
    debitAccountCode: '9999-MISC-EXPENSE',
    creditAccountCode: '1400-INVENTORY-STOVE',
    descriptionTemplate: 'Removed {{quantity}} stoves from inventory',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_sale_discount',
    name: 'Stove Sale Discount',
    debitAccountCode: '4201-REV-DISCOUNT',
    creditAccountCode: '4102-REV-STOVE',
    descriptionTemplate: 'Applied discount on stove sale for {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_return',
    name: 'Stove Return',
    debitAccountCode: '1400-INVENTORY-STOVE',
    creditAccountCode: '1100-ASSET-AR',
    descriptionTemplate: 'Returned {{quantity}} stoves from {{customerName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'stove_internal_transfer',
    name: 'Stove Internal Transfer',
    debitAccountCode: '1501-ASSET-INTERNAL-TRANSFER',
    creditAccountCode: '1400-INVENTORY-STOVE',
    descriptionTemplate: 'Transferred {{quantity}} stoves internally',
    categoryType: 'non_cash',
    isActive: true,
  },

  /* ========================== SHOPS ============================ */
  {
    code: 'shop_due_payment',
    name: 'Shop Due Payment',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '1102-AR-SHOPS',
    descriptionTemplate: 'Shop {{shopName}} cleared due payment',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'shop_cylinder_exchange_cash',
    name: 'Shop Cylinder Exchange (Cash)',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '4100-REV-CYL',
    descriptionTemplate: 'Cash exchange: shop {{shopName}} received {{quantity}} cylinders',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'shop_cylinder_exchange_credit',
    name: 'Shop Cylinder Exchange (Credit)',
    debitAccountCode: '1102-AR-SHOPS',
    creditAccountCode: '4100-REV-CYL',
    descriptionTemplate: 'Credit exchange: shop {{shopName}} received {{quantity}} cylinders',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'shop_regulator_sale_cash',
    name: 'Shop Regulator Sale (Cash)',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '4101-REV-REG',
    descriptionTemplate: 'Cash sale of regulators to shop {{shopName}}',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'shop_regulator_sale_credit',
    name: 'Shop Regulator Sale (Credit)',
    debitAccountCode: '1102-AR-SHOPS',
    creditAccountCode: '4101-REV-REG',
    descriptionTemplate: 'Credit sale of regulators to shop {{shopName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
  {
    code: 'shop_stove_sale_cash',
    name: 'Shop Stove Sale (Cash)',
    debitAccountCode: '1000-ASSET-CASH',
    creditAccountCode: '4102-REV-STOVE',
    descriptionTemplate: 'Cash sale of stoves to shop {{shopName}}',
    categoryType: 'cash_inflow',
    isActive: true,
  },
  {
    code: 'shop_stove_sale_credit',
    name: 'Shop Stove Sale (Credit)',
    debitAccountCode: '1102-AR-SHOPS',
    creditAccountCode: '4102-REV-STOVE',
    descriptionTemplate: 'Credit sale of stoves to shop {{shopName}}',
    categoryType: 'non_cash',
    isActive: true,
  },
];

/**

* @function seedBaseTxCategories
* @description
* Seeds the TxCategory collection with default transaction categories.
*
* @param {string} storeId - The ID of the store to seed the categories for.
  */
const seedBaseTxCategories = async (storeId: string): Promise<void> => {
  const count = await TxCategory.countDocuments({ store: storeId });
  if (count > 0) {
    console.log('[Seed] TxCategory collection already seeded.');
    return;
  }

  const categoryListToInsert = defaultTxCategoryList.map(category => ({
    ...category,
    store: new Types.ObjectId(storeId),
  }));

  await TxCategory.insertMany(categoryListToInsert);
  console.log('[Seed] Inserted extended default TxCategoryList.');
};

export default seedBaseTxCategories;
